[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://unihackfest-web.netlify.app/*"
  to = "https://unisynapse-web.netlify.app/:splat"
  status = 301
  force = true
